
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RBRACK = 5;
  public static final int ELSE = 18;
  public static final int COPER = 11;
  public static final int LogO = 13;
  public static final int BOPM = 2;
  public static final int WHILE = 20;
  public static final int TER = 23;
  public static final int LBRACK = 4;
  public static final int TRUE = 21;
  public static final int IF = 17;
  public static final int RCBRACK = 7;
  public static final int ROPER = 15;
  public static final int ID = 8;
  public static final int LogA = 12;
  public static final int NUM = 10;
  public static final int IDOPER = 16;
  public static final int BOMDP = 3;
  public static final int EOF = 0;
  public static final int FALSE = 22;
  public static final int error = 1;
  public static final int LCBRACK = 6;
  public static final int FOR = 19;
  public static final int AOPER = 9;
  public static final int LogX = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BOPM",
  "BOMDP",
  "LBRACK",
  "RBRACK",
  "LCBRACK",
  "RCBRACK",
  "ID",
  "AOPER",
  "NUM",
  "COPER",
  "LogA",
  "LogO",
  "LogX",
  "ROPER",
  "IDOPER",
  "IF",
  "ELSE",
  "FOR",
  "WHILE",
  "TRUE",
  "FALSE",
  "TER"
  };
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[5]=new String("RBRACK");
		TT[18]=new String("ELSE");
		TT[11]=new String("COPER");
		TT[13]=new String("LogO");
		TT[2]=new String("BOPM");
		TT[20]=new String("WHILE");
		TT[23]=new String("TER");
		TT[4]=new String("LBRACK");
		TT[21]=new String("TRUE");
		TT[17]=new String("IF");
		TT[7]=new String("RCBRACK");
		TT[15]=new String("ROPER");
		TT[8]=new String("ID");
		TT[12]=new String("LogA");
		TT[10]=new String("NUM");
		TT[16]=new String("IDOPER");
		TT[3]=new String("BOMDP");
		TT[0]=new String("EOF");
		TT[22]=new String("FALSE");
		TT[1]=new String("error");
		TT[6]=new String("LCBRACK");
		TT[19]=new String("FOR");
		TT[9]=new String("AOPER");
		TT[14]=new String("LogX");
	}
public String getTT(int i){return TT[i];}
}

