
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int BOPM = 2;
  public static final int LogA = 12;
  public static final int COMMENT = 36;
  public static final int CASE = 33;
  public static final int LCBRACK = 6;
  public static final int RCBRACK = 7;
  public static final int SL_COMMENT = 37;
  public static final int FOR = 19;
  public static final int ROPER = 15;
  public static final int COMMA = 26;
  public static final int CLASS = 38;
  public static final int DATATYPE = 25;
  public static final int BOMDP = 3;
  public static final int NUM = 10;
  public static final int LSBRACK = 28;
  public static final int IF = 17;
  public static final int COPER = 11;
  public static final int ID = 8;
  public static final int RSBRACK = 29;
  public static final int EOF = 0;
  public static final int RETURN = 31;
  public static final int TRUE = 22;
  public static final int NEW = 30;
  public static final int error = 1;
  public static final int SLIT = 39;
  public static final int BREAK = 35;
  public static final int SWITCH = 32;
  public static final int LBRACK = 4;
  public static final int COL = 27;
  public static final int ELSE = 18;
  public static final int RBRACK = 5;
  public static final int WHILE = 20;
  public static final int DEFAULT = 34;
  public static final int LogX = 14;
  public static final int IDOPER = 16;
  public static final int TER = 24;
  public static final int LogO = 13;
  public static final int FALSE = 23;
  public static final int DO = 21;
  public static final int AOPER = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BOPM",
  "BOMDP",
  "LBRACK",
  "RBRACK",
  "LCBRACK",
  "RCBRACK",
  "ID",
  "AOPER",
  "NUM",
  "COPER",
  "LogA",
  "LogO",
  "LogX",
  "ROPER",
  "IDOPER",
  "IF",
  "ELSE",
  "FOR",
  "WHILE",
  "DO",
  "TRUE",
  "FALSE",
  "TER",
  "DATATYPE",
  "COMMA",
  "COL",
  "LSBRACK",
  "RSBRACK",
  "NEW",
  "RETURN",
  "SWITCH",
  "CASE",
  "DEFAULT",
  "BREAK",
  "COMMENT",
  "SL_COMMENT",
  "CLASS",
  "SLIT"
  };
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[2]=new String("BOPM");
		TT[12]=new String("LogA");
		TT[36]=new String("COMMENT");
		TT[33]=new String("CASE");
		TT[6]=new String("LCBRACK");
		TT[7]=new String("RCBRACK");
		TT[37]=new String("SL_COMMENT");
		TT[19]=new String("FOR");
		TT[15]=new String("ROPER");
		TT[26]=new String("COMMA");
		TT[38]=new String("CLASS");
		TT[25]=new String("DATATYPE");
		TT[3]=new String("BOMDP");
		TT[10]=new String("NUM");
		TT[28]=new String("LSBRACK");
		TT[17]=new String("IF");
		TT[11]=new String("COPER");
		TT[8]=new String("ID");
		TT[29]=new String("RSBRACK");
		TT[0]=new String("EOF");
		TT[31]=new String("RETURN");
		TT[22]=new String("TRUE");
		TT[30]=new String("NEW");
		TT[1]=new String("error");
		TT[39]=new String("SLIT");
		TT[35]=new String("BREAK");
		TT[32]=new String("SWITCH");
		TT[4]=new String("LBRACK");
		TT[27]=new String("COL");
		TT[18]=new String("ELSE");
		TT[5]=new String("RBRACK");
		TT[20]=new String("WHILE");
		TT[34]=new String("DEFAULT");
		TT[14]=new String("LogX");
		TT[16]=new String("IDOPER");
		TT[24]=new String("TER");
		TT[13]=new String("LogO");
		TT[23]=new String("FALSE");
		TT[21]=new String("DO");
		TT[9]=new String("AOPER");
	}
public String getTT(int i){return TT[i];}
}

